### ISSUE TITLE
Object Detection Example

### ISSUE THREAD

**Issue by aribornstein** [GlastonburyC/coord-conv-pytorch#1]
Is there an example code integrating this with FasterRCNN as mentioned in the paper?

It seems to me like this solution has potential impact on localization tasks applied to OCR. I'd be curious to see what impact it would have on the ICDAR 2013 Table Competition dataset.

See https://arxiv.org/pdf/1804.06236.pdf for

**Comment by GlastonburyC** [comment]
Hi - Not that I know of.
